services:
  db:
    image: mysql:8.0
    container_name: becas_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistemabecas
    ports:
      - "3307:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - becas_data:/var/lib/mysql

volumes:
  becas_data: